### ISSUE TITLE
 python setup.py build develop 报错

### ISSUE THREAD

**Issue by HefengRAY** [HuangLian126/DGFIDaCL#1]
running build
running build_py
running build_ext
building 'maskrcnn_benchmark._C' extension
Emitting ninja build file /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.0
g++ -pthread -B /home/ub/anaconda3/envs/metadetr/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/ub/anaconda3/envs/metadetr/compiler_compat -L/home/ub/anaconda3/envs/metadetr/lib -Wl,-rpath=/home/ub/anaconda3/envs/metadetr/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cpu/nms_cpu.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/nms.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/vision.o -L/home/ub/anaconda3/envs/metadetr/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-37/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so
g++: error: /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o: 没有那个文件或目录
g++: error: /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1

我的环境配置：
CUDA 11.1 
PYTORCH 1.10
请问有什么解决的办法吗

**Comment by HuangLian126** [comment]
我觉得是版本的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月21日(周二) 下午4:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HuangLian126/DGFIDaCL]  python setup.py build develop 报错 (Issue #1)




 
running build
 running build_py
 running build_ext
 building 'maskrcnn_benchmark._C' extension
 Emitting ninja build file /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/build.ninja...
 Compiling objects...
 Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
 1.11.0
 g++ -pthread -B /home/ub/anaconda3/envs/metadetr/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/ub/anaconda3/envs/metadetr/compiler_compat -L/home/ub/anaconda3/envs/metadetr/lib -Wl,-rpath=/home/ub/anaconda3/envs/metadetr/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cpu/nms_cpu.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/SigmoidFocalLoss_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_kernel_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_kernel_cuda.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/nms.o /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/vision.o -L/home/ub/anaconda3/envs/metadetr/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-37/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so
 g++: error: /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_conv_cuda.o: 没有那个文件或目录
 g++: error: /media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/build/temp.linux-x86_64-cpython-37/media/ub/eb78aac6-ede5-4037-8e5c-179e82f06841/FSOD_PROJECT/DGFIDaCL-main/maskrcnn_benchmark/csrc/cuda/deform_pool_cuda.o: 没有那个文件或目录
 error: command '/usr/bin/g++' failed with exit code 1
 
我的环境配置：
 CUDA 11.1
 PYTORCH 1.10
 请问有什么解决的办法吗

**Comment by HefengRAY** [comment]
>
